repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  name: dbt-home-test
  description: "OakNorth DBT Home Test"
  topics: "squad::Data Platform, mission::Platform, product::Platform, environment::Pre-Production"
