
version: 2

models:
  - name: stg_customers_adjusted
    description: "The customer reference table"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        # tests:
        #   - unique
        #   - not_null
      - name: name
        description: "The name of customer"
        # tests:
        #   - not_null
      - name: date_of_birth
        description: "The date of birth of customer"
        # tests:
        #   - unique
        #   - not_null
      - name: joined_date
        description: "The date of joining of customer"
        # tests:
        #   - not_null

  - name: stg_transactions_adjusted
    description: "A starter dbt model"
    columns:
      - name: transaction_id
        description: "The primary key for this table"
        # tests:
        #   - unique
        #   - not_null
      - name: customer_id
        description: "The primary key for this table"
        # tests:
        #   - unique
        #   - not_null
      - name: transaction_date
        description: "The primary key for this table"
        # tests:
        #   - unique
        #   - not_null
      - name: amount
        description: "The primary key for this table"
        # tests:
        #   - unique
        #   - not_null
